[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Remove or comment out the Next.js plugin section if it exists
# [[plugins]]
# package = "@netlify/plugin-nextjs"
